import type { Metadata } from "next";
import { Header } from "@/components/layout/Header";
import { MobileHeader } from "@/components/mobile/MobileHeader";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            {/* <Header />
            <MobileHeader /> */}
            <main className="my-20">
                {children}
            </main>
        </>
    );
}
